core/urls.py
from django.urls import path
from core import views

app_name="core"
urlpatterns=[
    # common
    path("",views.HomeView.as_view(),name="home"),
    path("about/",views.AboutView.as_view(),name="about_us"),
    path("action/",views.ActionView.as_view(),name="choose_action"),
    # search
    path("product/search/",views.ProductSearchView.as_view(),name="product_search"),
    # feedback
    path("feedback_create/",views.FeedbackCreateView.as_view(),name="feedback_create"),
    path("feedback_list/",views.FeedbackListView.as_view(),name="feedback_list"),
    # product
    path("view_list/",views.ProductListView.as_view(),name="product_list"),
    path("card/<int:pk>/product/purchase/",views.ProductPurchaseView.as_view(),name="product_purchase"),
    # category
    path("card_list/",views.CardListView.as_view(),name="card_list"),
    # product by card
    path("product_by_card/<int:pk>/list/",views.ProductByCardView.as_view(),name="product_by_card"),
    # cart ckeckout
    path("cart/checkout/",views.CheckOutView.as_view(),name="cart_checkout"),
    # product summary
    path("product_summary/",views.ProductSummaryView.as_view(),name="product_summary"),
    # payment
    path("payment/",views.PaymentView.as_view(),name="payment"),
    # success
    path("success/",views.SuccessView.as_view(),name="success"),
]

online_ration_delivery/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("core.urls",namespace="core")),
    path("user/",include("user.urls",namespace="user")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from core import views
from user import views


app_name = "user"

urlpatterns = [
    path("sign_up/", views.UserCreateView.as_view(), name = "user_signup"),
    path("login/", views.UserLoginView.as_view(), name = "user_login"),
    path("logged_out/",views.UserLogoutView.as_view(),name="user_logout"),
    # card details
    path("card_details/",views.CardDetailView.as_view(),name="card_details"),
    # profile
    path("profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/<int:pk>/detail/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/",views.ProfileUpdateView.as_view(),name="profile_update"), 
    # address
    path("add_address/",views.AddressCreateView.as_view(),name="add_address"),
    path("address/<int:pk>/update/",views.AddressUpdateView.as_view(),name="address_update"),
    path("product_delivery/",views.DeliveryDetailView.as_view(),name="product_delivery"),
]

templates/delivery/address_update.html
{% extends 'base.html' %} 
{% block content %}

<div class="container py-5">
    <div class="row">
      <div class="col">
        <table>
          <thead class="font-4 poppins">
            <tr><br>
              <th class="text-primary"><label class="fa-solid fa-phone"></label> Contact Details</th>
            </tr>
          </thead>
          <form>
          <tbody class="font times">
            <tr>
              <td class="p-2">Name :</td>
              <td><div class="col-sm-10">
                <input type="text" class="form-control">
              </div>
          </td>
            </tr>
            <tr>
              <td class="p-2">Phone Number :</td>
              <td><div class="col-sm-10">
                <input type="text" class="form-control">
              </div>
          </td>
            </tr>
          </tbody>
        </form>
        </table>
        <br />
        <table>
          <thead class="font-4 poppins">
            <tr><br>
              <th class="text-primary"><label class="fa-solid fa-location-dot"></label> Address</th>
            </tr>
          </thead>
          <tbody class="font times">
            <tr>
              <td class="p-2">House No / Building Name :</td>
              <td><div class="col-sm-10">
                <input type="text" class="form-control">
              </div>
          </td>
            </tr>
            <tr>
              <td class="p-2">Road Name / Area / Colony :</td>
              <td><div class="col-sm-10">
                <input type="text" class="form-control">
              </div>
          </td>
            </tr>
            <tr>
              <td class="p-2">Pincode :</td>
              <td><div class="col-sm-10">
                <input type="text" class="form-control">
              </div></td>
            </tr>
            <tr>
              <td class="p-2">City :</td>
              <td><div class="col-sm-10">
                <input type="text" class="form-control">
              </div></td>
            </tr>
            <tr>
              <td class="p-2">State :</td>
              <td><div class="col-sm-10">
                <input type="text" class="form-control">
              </div></td>
            </tr>
            <tr>
              <td class="p-2">Nearby Locations(Optional) :</td>
              <td><div class="col-sm-10">
                <input type="text" class="form-control">
              </div></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col text-end">
          <a href="{% url 'core:product_delivery' %}"><button class="btn btn-info font roboto fst-italic" type="submit">Save Address and Continue</button></a>
      </div>
    </div>
  </div>




{% endblock content %}

templates/delivery/delivery.html
{% extends 'base.html' %} {% block content %}

<section class="bg-delivery">
<div class="container py-5">
  <div class="position-relative m-4">
    <div class="progress" style="height: 1px">
      <div
        class="progress-bar"
        role="progressbar"
        aria-label="Progress"
        style="width: 0%"
        aria-valuenow="50"
        aria-valuemin="0"
        aria-valuemax="100"
      ></div>
    </div>
    <button
      type="button"
      class="position-absolute top-0 start-0 translate-middle btn btn-sm btn-primary rounded-pill"
      style="width: 2rem; height: 2rem"
    >
      1
      <p class="text-black p-2 times"><b>Delivery</b></p>
    </button>
    <button
      type="button"
      class="position-absolute top-0 start-50 translate-middle btn btn-sm btn-secondary rounded-pill"
      style="width: 2rem; height: 2rem"
    >
      2
      <p class="text-muted p-2 times"><b>payment</b></p>
    </button>
    <button
      type="button"
      class="position-absolute top-0 start-100 translate-middle btn btn-sm btn-secondary rounded-pill"
      style="width: 2rem; height: 2rem"
    >
      3
      <p class="text-muted p-2 times"><b>Summary</b></p>
    </button>
  </div>
  <br />
  <div>
    <a href="{% url 'user:add_address' %}"
      ><label class="font times"
        ><i class="fa-solid fa-plus"></i>ADD NEW ADDRESS</label
      ></a
    >
  </div>
  <br />
  {% if user.profilemodel %}
  <div class="card">
    <div class="card-body">
      <div class="card-title font times">
        <p><b>{{user.profilemodel.first_name}} {{user.profilemodel.last_name}}</b></p>
      </div>
        <div class="card-text times font-5">
          {% for address in user.profilemodel.address.all %}
          <p>{{address}}</p>
          {% empty %}
          <a href="" class="btn btn-primary">Create address</a>
          {% endfor %}
          <p>{{user.profilemodel.phone_number}}</p>
          <a href=""><button class="btn btn-info grey font-1">EDIT</button></a>
        </div>
    </div>
    <div class="text-end m-3 font p-2">
      <a href="{% url 'core:payment' %}" ><button class="btn btn-primary">Deliver To This Address</button></a>
    </div>
    {% endif %}    
  </div>
</div>
</section>
{% endblock content %}

templates/delivery/new_address.html
{% extends 'base.html' %} {% block content %}

<div class="container py-5">
  <div class="row">
    <div class="col">
      <form action="" method="post">
        {% csrf_token %}
        <table>
          <thead class="font-4 poppins">
            <tr><br>
              <th class="text-primary"><label class="fa-solid fa-phone"></label> Contact Details</th>
            </tr>
          </thead>
          <form>
          <tbody class="font times">
            <tr>
              <td class="p-2">Name :</td>
              <td><div class="col-sm-10">
                <input type="text" class="form-control">
              </div>
          </td>
            </tr>
            <tr>
              <td class="p-2">Phone Number :</td>
              <td><div class="col-sm-10">
                <input type="text" class="form-control">
              </div>
          </td>
            </tr>
          </tbody>
       
        </table>
      <br />
      <table>
        <thead class="font-4 poppins">
          <tr><br>
            <th class="text-primary"><label class="fa-solid fa-location-dot"></label> Address</th>
          </tr>
        </thead>
        <tbody class="font times">
          <tr>
            <td class="p-2">House No / Building Name :</td>
            <td><div class="col-sm-10">
              <input type="text" class="form-control">
            </div>
        </td>
          </tr>
          <tr>
            <td class="p-2">Road Name / Area / Colony :</td>
            <td><div class="col-sm-10">
              <input type="text" class="form-control">
            </div>
        </td>
          </tr>
          <tr>
            <td class="p-2">Pincode :</td>
            <td><div class="col-sm-10">
              <input type="text" class="form-control">
            </div></td>
          </tr>
          <tr>
            <td class="p-2">City :</td>
            <td><div class="col-sm-10">
              <input type="text" class="form-control">
            </div></td>
          </tr>
          <tr>
            <td class="p-2">State :</td>
            <td><div class="col-sm-10">
              <input type="text" class="form-control">
            </div></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col text-end">
      <button class="btn btn-info font roboto fst-italic" type="submit">Save Address and Continue</button>
    </div>
  </form>
  </div>
</div>

{% endblock content%}