core/urls.py
from django.urls import path
from core import views

app_name="core"
urlpatterns=[
    # common
    path("",views.HomeView.as_view(),name="home"),
    path("about/",views.AboutView.as_view(),name="about_us"),
    path("action/",views.ActionView.as_view(),name="choose_action"),
    # search
    path("product/search/",views.ProductSearchView.as_view(),name="product_search"),
    # feedback
    path("feedback_create/",views.FeedbackCreateView.as_view(),name="feedback_create"),
    path("feedback_list/",views.FeedbackListView.as_view(),name="feedback_list"),
    # product
    path("view_list/",views.ProductListView.as_view(),name="product_list"),
    path("card/<int:pk>/product/purchase/",views.ProductPurchaseView.as_view(),name="product_purchase"),
    # category
    path("card_list/",views.CardListView.as_view(),name="card_list"),
    # product by card
    path("product_by_card/<int:pk>/list/",views.ProductByCardView.as_view(),name="product_by_card"),
    # cart ckeckout
    path("cart/checkout/",views.CheckOutView.as_view(),name="cart_checkout"),
    # product summary
    path("product_summary/",views.ProductSummaryView.as_view(),name="product_summary"),
    # payment
    path("payment/",views.PaymentView.as_view(),name="payment"),
    # success
    path("success/",views.SuccessView.as_view(),name="success"),
]

online_ration_delivery/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("core.urls",namespace="core")),
    path("user/",include("user.urls",namespace="user")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from core import views
from user import views


app_name = "user"

urlpatterns = [
    path("sign_up/", views.UserCreateView.as_view(), name = "user_signup"),
    path("login/", views.UserLoginView.as_view(), name = "user_login"),
    path("logged_out/",views.UserLogoutView.as_view(),name="user_logout"),
    # card details
    path("card_details/",views.CardDetailView.as_view(),name="card_details"),
    # profile
    path("profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/<int:pk>/detail/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/",views.ProfileUpdateView.as_view(),name="profile_update"), 
    # address
    path("add_address/",views.AddressCreateView.as_view(),name="add_address"),
    path("address/<int:pk>/update/",views.AddressUpdateView.as_view(),name="address_update"),
    path("product_delivery/",views.DeliveryDetailView.as_view(),name="product_delivery"),
]

core/models.py
from django.db import models
from django.conf import settings

USER = settings.AUTH_USER_MODEL


class TimeStamp(models.Model):
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# feedback model
class FeedbackModel(TimeStamp, models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField()
    subject = models.CharField(max_length=120)
    message = models.TextField(max_length=500)

    def __str__(self):
        return f"{self.name}"


# unit model
class UnitModel(TimeStamp, models.Model):
    name = models.CharField(max_length=64)
    symbol = models.CharField(max_length=8)
    convertion_rate = models.FloatField()
    secondary = models.ForeignKey(
        "self", on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return f"{self.name}"


# product category model
class CategoryModel(TimeStamp, models.Model):
    name = models.CharField(max_length=64)
    parent = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.name}"


# product model
class ProductModel(TimeStamp, models.Model):
    name = models.CharField(max_length=64)
    price = models.FloatField(max_length=100)
    unit = models.ForeignKey(
        UnitModel, on_delete=models.SET_NULL, null=True, blank=True
    )
    category = models.ManyToManyField(CategoryModel)
    image = models.ImageField(
        upload_to="product/image",
        default="default/product.png",
    )

    def __str__(self):
        return f"{self.name}"


# category of cards
class CardModel(TimeStamp, models.Model):
    class CardTypeChoice(models.TextChoices):
        APL = "apl", "APL"
        BPL = "bpl", "BPL"
        AAY = "aay", "AAY"
        NPNS = "npns", "NPNS"

    name = models.CharField(max_length=64)
    description = models.TextField(max_length=500)
    type = models.CharField(max_length=5, choices=CardTypeChoice.choices)

    def __str__(self):
        return f"{self.name}({self.CardTypeChoice(self.type).name})"


# stock model
class StockModel(TimeStamp, models.Model):
    card = models.ForeignKey(CardModel, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    quantity = models.FloatField()

    def __str__(self):
        return f"{self.product}(Qty - {self.quantity})"


class QuotaModel(TimeStamp, models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE)
    stock = models.ForeignKey(StockModel, on_delete=models.CASCADE)
    is_available = models.BooleanField(default=True)

    def __str__(self):
        name = f"{self.stock} is not available for {self.user}"
        if self.is_available:
            name = f"{self.stock} is available for {self.user}"
        return name


#  cart
class CartModel(TimeStamp, models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE)
    checked_out = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user}"

    def items(self):
        cart_items = CartItemModel.objects.filter(cart=self, status=True)
        return cart_items


# cart item model
class CartItemModel(TimeStamp, models.Model):
    cart = models.ForeignKey(CartModel, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    quantity = models.FloatField(default=0)

    def __str__(self):
        return f"{self.product}({self.quantity})"

core/forms.py
from django import forms
from core import models

# for feedback
class FeedbackForm(forms.ModelForm):
    class Meta:
        model = models.FeedbackModel
        exclude = ("status",)


# for product
class ProductForm(forms.ModelForm):
    class Meta:
        model = models.ProductModel
        exclude = ("status", "updated_on", "created_on")


class ProductPurchaseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        card_id = kwargs.pop("card")
        super().__init__(*args, **kwargs)
        queryset = models.ProductModel.objects.filter(stockmodel__card__id=card_id)
        self.fields.update(
            {
                "products": forms.ModelMultipleChoiceField(queryset=queryset),
            }
        )

core/views.py
from django.shortcuts import redirect
from django.views import generic as views
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from core import models as core_models
from core.forms import FeedbackForm, ProductForm, ProductPurchaseForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import F,Q

# ---------common-----------
# home view
class HomeView(views.TemplateView):
    template_name = "core/home.html"
    extra_context = {"cards": core_models.CardModel.objects.all()}


# about_us view
class AboutView(views.TemplateView):
    template_name = "core/about_us.html"


# choose actions view
class ActionView(views.TemplateView):
    template_name = "core/actions.html"
    extra_context = {"products": core_models.ProductModel.objects.all()}


# ----------product----------

# view pdts wrt card
class ProductByCardView(views.ListView):
    template_name = "core/actions.html"
    model = core_models.ProductModel
    context_object_name = "products"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        card = core_models.CardModel.objects.get(id=self.kwargs.get("pk"))
        context.update({"card": card})
        return context

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        card_pk = self.kwargs.get("pk", None)
        qs = qs.filter(stockmodel__card__id=card_pk)
        return qs


# card category list
class CardListView(views.ListView):
    template_name = "core/home.html"
    model = core_models.CardModel
    context_object_name = "categories"


# view product list
class ProductListView(views.ListView):
    template_name = "product/product_list.html"
    model = core_models.ProductModel
    form_class = ProductForm


# view product purchase
class ProductPurchaseView(LoginRequiredMixin, views.FormView):
    template_name = "product/product_purchase.html"
    model = core_models.ProductModel
    form_class = ProductPurchaseForm
    success_url = reverse_lazy("core:cart_checkout")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get("pk", None)
        products = core_models.ProductModel.objects.filter(stockmodel__card__id=pk)
        context.update({"products": products})
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        card = self.kwargs.get("pk")
        kwargs.update({"card": card})
        return kwargs
    # product added to cart
    def form_valid(self, form):
        print("#DEBUG: form data ", form.cleaned_data)
        data = form.cleaned_data
        products = data.get("products", None)
        cart, created_cart = core_models.CartModel.objects.get_or_create(
            user=self.request.user,
            checked_out=False,
        )
        for product in products:
            cart_item, created_item = core_models.CartItemModel.objects.get_or_create(
                product=product,
                cart=cart,
                quantity=product.stockmodel.quantity,
            )
        return super().form_valid(form)


# cart checkout
class CheckOutView(LoginRequiredMixin,views.View):
    template_name="product/checkout.html"
    model=core_models.CartModel




# search view
class ProductSearchView(views.ListView):
    template_name = "product/product_list.html"
    model = core_models.ProductModel
    context_object_name = "products"

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        q = self.request.GET.get("q", None)
        qs = qs.filter(Q(name__icontains=q) | Q(product__name__icontains=q))
        return qs


# -----------feedback-----------
# feedback create
class FeedbackCreateView(views.CreateView):
    template_name = "feedback/feedback_create.html"
    model = core_models.FeedbackModel
    form_class = FeedbackForm
    success_url = reverse_lazy("core:home")


# feedback list
class FeedbackListView(views.ListView):
    template_name = "feedback/feedback_list.html"
    model = core_models.FeedbackModel
    context_object_name = "feedbacks"


# -----------final----------
# payment
class PaymentView(views.TemplateView):
    template_name = "core/payment.html"


# product summary
class ProductSummaryView(views.TemplateView):
    template_name = "core/summary.html"


# success
class SuccessView(views.TemplateView):
    template_name = "core/success.html"

templates/core/about_us.html
{% extends 'base.html' %} {% block content %}

<body class="bg-image-about">
  <div class="container py-5">
    <!-- collapse -->
    <p class="text-end">
      <a class="btn btn-dark font-5 roboto" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">NOTICE</a>
      <button class="btn btn-dark font-5 roboto" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">
        RCMS E-SERVICES </button>
    </p>
    <div class="row">
      <div class="col">
        <div class="collapse multi-collapse" id="multiCollapseExample1">
          <div class="card card-body font-1 times">
            <p>E-Services for Ration Card Management System was launched on 18th July 2018 in two taluks and enhanced throughout the State on 4th August 2018.</p>
            <hr>
            <p>Ration Card holders and residents will be able to register and log into the e-Citizen service portal and avail the services.</p>
          </div>
        </div>
      </div>
    </div>
      <div class="col">
        <div class="collapse multi-collapse" id="multiCollapseExample2">
          <div class="card card-body font-1 times">
            <p>e-Services(RCMS) intend to provide services related to Ration Card management System to citizens & ration card holders through Common Service Centers(CSC) which are easily accessible.</p><hr>
            <p>Applications submitted by the CSCs are processed using the work-flow based web enabled e-services at the Taluk Supply Offices/City Rationing Offices in the State.</p><hr>
            <p>e-Services utilizes backend computerization to e-enable the delivery of services and ensures transparency and uniform application of rules. It helps in minimizing time and effort to provide prompt and effective service to the public.</p>
          </div>
        </div>
      </div>
    
  
    <div class="row">
      <h1 class="font-2 text-muted"><b>ABOUT</b></h1>
      <br>
      <p class="text-justify font text-muted">
        Ration shops are structured to provide food stocks and other household
        things to the poor sections of the society. They give the stocks to the
        poor individuals as settled based on the Issue price. The issue price is
        the cost chosen by the government on which the ration shops will offer
        the goods to the poor ones.Locally these are known as ration shops and
        public distribution shops, and chiefly sell wheat, rice and sugar at a
        price lower than the market price called Issue Price. Other essential
        commodities may also be sold. To buy items one must have a ration card.
        It is an online platform to purchase the ration items online by just a
        single touch.
      </p>
    </div>
  </div>
  <hr />
  <div class="container text-muted">
    <p class="font-2">For more Details :</p>
    <div class="card">
      <div class="card-body">
        <div class="card-title font">
          <p><label class="fa-solid fa-phone"></label><b> Contact US :</b></p>
          <div class="card-text">
            <table>
              <tbody>
                <tr>
                  <td>Name :</td>
                  <td>---------</td>
                </tr>
                <tr>
                  <td>Email :</td>
                  <td>---------</td>
                </tr>
                <tr>
                  <td>Phone No :</td>
                  <td>---------</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br><br>
</body>
{% endblock content %}

templates/core/actions.html
{% extends 'base.html' %} {% block content %}

<body class="bg-image-action">
  <div class="container py-5">
    <table class="table">
      <tbody>
        <tr>
          <td class="font-2 poppins"><b>CARD TYPE :- {{category.name}}</b></td>
          <td>
            {% if user.is_authenticated %}
            <a href="{% url 'core:product_purchase' card.id %}"><button class="btn btn-primary font roboto">Purchase
                Item</button></a>
            {% else %}
            <a href="{% url 'user:user_login' %}"><button class="btn btn-primary font roboto">Purchase Item</button></a>
            {% endif %} 
          </td>
          <!--offcanvas-->
          <td>
            <a data-bs-toggle="offcanvas" href="#offcanvasExample" aria-controls="offcanvasExample"><button
                type="button" class="btn btn-primary font roboto">Other Actions</button></a>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasExample"
              aria-labelledby="offcanvasExampleLabel">
              <div class="offcanvas-header">
                <h5 class="offcanvas-title font times" id="offcanvasExampleLabel">Choose Any Action</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
              </div>
              <div class="offcanvas-body">
                <div class="card font poppins">
                  <div class="card-body">
                    <div class="card-text"><a href="{% url 'user:card_details' %}" class="u">
                        View Ration-Card details
                      </a>
                    </div>
                  </div>
                </div>
                <div class="card font poppins">
                  <div class="card-body">
                    <div class="card-text">
                      <a href="" class="u">
                        
                        Other available offers
                      </a><span class="badge bg-primary rounded-pill">1</span>
                    
                      
                    </div>
                  </div>
                </div>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="container py-5">
      <p class="font times"><b>Available Product Details</b></p>
      <div class="row row-cols-md-3 g-3">
        {% for product in products %}
        <div class="col">
          <div class="card">
            <img src="" class="card-img-top" alt="..." height="200px" />
            <div class="card-body">
              <h5 class="card-title font-4 roboto">{{product.name}}</h5>
              <p class="card-text font times">Price: {{product.price}}</p>
              <p class="card-text font-1 poppins" style="height: 50px;">Available Quantity: {{product.stockmodel.quantity}} {{product.unit.symbol}}
              </p>
              <p class="card-text text-muted fst-italic">
                Last updated: {{product.updated_on|date}}
              </p>
            </div>
          </div>
        </div>
          {% empty %}
          <div class="col">
            <p class="font">No Product Found</p>
          </div>
          {% endfor %}

        
      </div>
    </div>
  </div>
</body>

{% endblock content %}

templates/core/home.html
{% extends 'base.html' %} {% block content %}
<!-- header -->
<div class="container-fluid bg-image-home">
  <div class="container py-5">
    <p class="font-3 text-center roboto"><b>Online Ration Service</b></p>
    <p class="text-center font poppins fst-italic">
      Here is to remind your Ration is here! Wanna take a look
    </p>
  </div>
<!-- carousel -->
  <div class="container">
    <section class="hero-section">
      <div
        id="carouselExampleControls"
        class="carousel slide"
        data-bs-ride="carousel"
      >
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img
              src="media/default/img4.jpg"
              height="500px"
              class="d-block w-100"
              alt="..."
            />
          </div>
          <div class="carousel-item">
            <img
              src="media/default/img2.jpg"
              height="500px"
              class="d-block w-100"
              alt="..."
            />
          </div>
          <div class="carousel-item">
            <img
              src="media/default/img5.jpg"
              height="500px"
              class="d-block w-100"
              alt="..."
            />
          </div>
          <div class="carousel-item">
            <img
              src="media/default/img6.jpg"
              height="500px"
              class="d-block w-100"
              alt="..."
            />
          </div>
        </div>
        <button
          class="carousel-control-prev"
          type="button"
          data-bs-target="#carouselExampleControls"
          data-bs-slide="prev"
        >
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button
          class="carousel-control-next"
          type="button"
          data-bs-target="#carouselExampleControls"
          data-bs-slide="next"
        >
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </section>
  </div>
  <br />
  <section>
    <div class="container py-5">
      <div class="dropdown-center font roboto text-center">
        <label>Choose Your Card :</label>
        <button
          class="btn btn-primary active dropdown-toggle font-1"
          type="button"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          Select card
        </button>
        <ul class="dropdown-menu">
          {% for card in cards %}
          <li>
            <a
              class="dropdown-item link font-1 poppins"
              href="{% url 'core:product_by_card' card.id %}"
            >
              {{card}}
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </section>
</div>
{% endblock content %}

templates/core/offers.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    
</div>






{% endblock content %}

templates/core/payment.html
{% extends 'base.html' %} {% block content %}

<section class="bg-delivery">
<div class="container py-5">
    <div class="position-relative m-4">
      <div class="progress" style="height: 1px">
        <div
          class="progress-bar"
          role="progressbar"
          aria-label="Progress"
          style="width: 50%"
          aria-valuenow="50"
          aria-valuemin="0"
          aria-valuemax="100"
        ></div>
      </div>
      <button
        type="button"
        class="position-absolute top-0 start-0 translate-middle btn btn-sm btn-primary rounded-pill"
        style="width: 2rem; height: 2rem"
      >
        1<p class="text-muted p-2 times"><b>Delivery</b></p>
      </button>
      <button
        type="button"
        class="position-absolute top-0 start-50 translate-middle btn btn-sm btn-primary rounded-pill"
        style="width: 2rem; height: 2rem"
      >
        2<p class="text-black p-2 times"><b>payment</b></p>
      </button>
      <button
        type="button"
        class="position-absolute top-0 start-100 translate-middle btn btn-sm btn-secondary rounded-pill"
        style="width: 2rem; height: 2rem"
      >
        3<p class="text-muted p-2 times"><b>Summary</b></p>
      </button>
    </div>

    <div class="container py-5 font-5">
      <table class="table">
          <tbody>
              <tr>
                  <td>Select Payment Methods</td>
                  <td class="text-end"><i class="fa-sharp fa-solid fa-shield-check"></i> 100% SAFE PAYMENTS</td>
              </tr>
          </tbody>
      </table>

    <section>
    <div class="container">
      <p class="text-muted m-3 p-2 font">PAY ONLINE</p>
      <div class="form-check font-5">
        <input class="form-check-input" type="radio" name="flexRadioDefault">
        <label class="form-check-label" for="flexRadioDefault1">
          <a href="" class="u black">Razor Pay</a>
        </label>
      </div>
      <div class="form-check font-5">
        <input class="form-check-input" type="radio" name="flexRadioDefault">
        <label class="form-check-label" for="flexRadioDefault1">
          <a href="" class="u black">Net Banking</a>
        </label>
      </div>
      <div>
        <p class="text-muted m-3 p-2 font">PAY IN CASH</p>
        <div class="form-check font-5">
          <input class="form-check-input" type="radio" name="flexRadioDefault">
          <label class="form-check-label black" for="flexRadioDefault1">
            Cash On Delivery
          </label>
        </div>
    </div>
  </div>
  </section>

  <section>
    <div class="container py-5 font-5">
      <p><a href="" class="u black"><label>View price details</a>(No of items) :-</label></p>
      <p>Total product price :---------</p>
    </div>
    <div class="text-center bg-secondary font-5 white roboto p-2">clicking on <mark class="bg-warning">continue</mark> will not deduct any money</div>
  </section>

    <section>
      <div class="container py-5 font-5">
        <div class="row">
          <div class="col">
            <p>price ----</p>
            <a href="" class="u black"><label>View price details</label></a>
          </div>
          <div class="col text-end">
            <a href="{% url 'core:product_summary' %}"><button class="btn btn-primary font roboto">continue</button></a>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
</section>
  {% endblock content %}

templates/core/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- stylesheets -->
    <link
      rel="stylesheet"
      href="../../static/bootstrap-5.2.1-dist/css/bootstrap.css"
    />
    <link
      rel="stylesheet"
      href="../../static/fontawesome-free-6.2.0-web/css/all.css"
    />
    <link rel="stylesheet" href="../../static/css/style.css" />
    <title>Product Puchased</title>
</head>
<body>
    <div class="row">
        <div class="colspan-4 m-5">
            <div class=" position-absolute bottom-50 text-center">
                <i class="fa-regular fa-circle-check fa-8x text-primary"></i>
            </div>    
            <div class="position-absolute top-50 font-3">
                <p class="text-primary" style="font-family:times ;">Successfully Purchased</p>
            </div>
        </div>
    </div>
    
    





    <!-- scripts -->
    <script src="../../static/bootstrap-5.2.1-dist/js/bootstrap.bundle.min.js"></script>
    <script src="../../static/fontawesome-free-6.2.0-web/js/all.min.js"></script>
    <script src="../../static/js/script.js"></script>   
</body>
</html>

templates/core/summary.html
{% extends 'base.html' %} {% block content %}

<body class="bg-summary">
<div class="container py-5">
  <!-- progress bar -->
  <div class="position-relative m-4">
    <div class="progress" style="height: 1px">
      <div
        class="progress-bar"
        role="progressbar"
        aria-label="Progress"
        style="width: 100%"
        aria-valuenow="50"
        aria-valuemin="0"
        aria-valuemax="100"
      ></div>
    </div>
    <button
      type="button"
      class="position-absolute top-0 start-0 translate-middle btn btn-sm btn-primary rounded-pill"
      style="width: 2rem; height: 2rem"
    >
      1
      <p class="text-muted p-2 times"><b>Delivery</b></p>
    </button>

    <button
      type="button"
      class="position-absolute top-0 start-50 translate-middle btn btn-sm btn-primary rounded-pill"
      style="width: 2rem; height: 2rem"
    >
      2
      <p class="text-muted p-2 times"><b>payment</b></p>
    </button>

    <button
      type="button"
      class="position-absolute top-0 start-100 translate-middle btn btn-sm btn-primary rounded-pill"
      style="width: 2rem; height: 2rem"
    >
      3
      <p class="text-black p-2 times"><b>Summary</b></p>
    </button>
  </div>
  <br />
  <div>
    <label class="fa-light fa-cart-shopping-fast"></label>
    <label class="font times"> Delivery Estimated within 10 minutes</label>
  </div>
  <div class="card bg-card">
    <div class="card-body">
      <div class="card-title font-6 roboto">
        <p>Product Details</p><hr>
        <div class="card-text font poppins">
          <p>---------</p>
          <p>---------</p>
          <p>---------</p>
        </div>
      </div>
    </div>
  </div><br>
  <div class="card bg-card">
    <div class="card-body">
      <div class="card-title font-6 roboto">
        <p>Delivery Details</p><hr>
        <div class="card-text font poppins">
          <p>Name</p>
          <p>Phone No</p>
          <p>Address</p>
        </div>
      </div>
    </div>
  </div><br>
  <div class="card bg-card">
    <div class="card-body">
      <div class="card-title font-6 roboto">
        <p>Payment Mode</p>
        <div class="card-text font poppins">
          <p>----------</p>
        </div>
      </div>
    </div>
  </div><br>
  <div class="card bg-card">
    <div class="card-body">
      <div class="card-title font-6 roboto">
        <p>Price Details</p>
        <div class="card-text font poppins">
          <p>Order Total :------</p>
        </div>
      </div>
    </div>
  </div>
  <br />
  <div class="text-center">
    <a href="{% url 'core:success' %}"><button class="btn btn-primary font-4 roboto" type="button">
      Place Order
    </button></a>
  </div>
</div>
</body>

{% endblock content%}