core/urls.py
from django.urls import path
from core import views

app_name="core"
urlpatterns=[
    # common
    path("",views.HomeView.as_view(),name="home"),
    path("about/",views.AboutView.as_view(),name="about_us"),
    path("action/",views.ActionView.as_view(),name="choose_action"),
    # search
    path("product/search/",views.ProductSearchView.as_view(),name="product_search"),
    # feedback
    path("feedback_create/",views.FeedbackCreateView.as_view(),name="feedback_create"),
    path("feedback_list/",views.FeedbackListView.as_view(),name="feedback_list"),
    # product
    path("view_list/",views.ProductListView.as_view(),name="product_list"),
    path("card/<int:pk>/product/purchase/",views.ProductPurchaseView.as_view(),name="product_purchase"),
    # category
    path("card_list/",views.CardListView.as_view(),name="card_list"),
    # product by card
    path("product_by_card/<int:pk>/list/",views.ProductByCardView.as_view(),name="product_by_card"),
    # cart ckeckout
    path("cart/checkout/",views.CheckOutView.as_view(),name="cart_checkout"),
    # product summary
    path("product_summary/",views.ProductSummaryView.as_view(),name="product_summary"),
    # payment
    path("payment/",views.PaymentView.as_view(),name="payment"),
    # success
    path("success/",views.SuccessView.as_view(),name="success"),
]

online_ration_delivery/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("core.urls",namespace="core")),
    path("user/",include("user.urls",namespace="user")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from core import views
from user import views


app_name = "user"

urlpatterns = [
    path("sign_up/", views.UserCreateView.as_view(), name = "user_signup"),
    path("login/", views.UserLoginView.as_view(), name = "user_login"),
    path("logged_out/",views.UserLogoutView.as_view(),name="user_logout"),
    # card details
    path("card_details/",views.CardDetailView.as_view(),name="card_details"),
    # profile
    path("profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/<int:pk>/detail/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/",views.ProfileUpdateView.as_view(),name="profile_update"), 
    # address
    path("add_address/",views.AddressCreateView.as_view(),name="add_address"),
    path("address/<int:pk>/update/",views.AddressUpdateView.as_view(),name="address_update"),
    path("product_delivery/",views.DeliveryDetailView.as_view(),name="product_delivery"),
]

templates/includes/footer.html
    <!-- Footer -->
    <footer class="text-center text-lg-start footer font-5">
      <!-- Section: Social media -->
      <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
          <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
          <a
          class="btn text-white btn-floating m-1"
          style="background-color: #3b5998;"
          href="#!"
          role="button"
          ><i class="fab fa-facebook-f"></i
        ></a>
        <a
          class="btn text-white btn-floating m-1"
          style="background-color: #17d53aac;"
          href="#!"
          role="button"
          ><i class="fa-brands fa-whatsapp"></i>
        </a>
          <a
          class="btn text-white btn-floating m-1"
          style="background-color: #dd4b39;"
          href="#!"
          role="button"
          ><i class="fab fa-google"></i
        ></a>
        <a
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
        ></a>
        <a
        class="btn text-white btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
        ></a>
        </div>
        <!-- Right -->
      </section>
      <!-- Section: Social media -->

      <!-- Section: Links  -->
      <section class="">
        <div class="container text-center text-md-start mt-5">
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              <!-- Content -->
              <h6 class="text-uppercase fw-bold mb-4">
                <i class="fas fa-gem me-3"></i>ORD</h6>
            </div>
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">
                Useful links
              </h6>
              <p>
                <a href="{% url 'core:about_us' %}" class="text-reset">About us</a>
              </p>
              <p>
                <a href="{% url 'core:choose_action' %}" class="text-reset">products</a>
              </p>
              <p>
                <a href="#!" class="text-reset">settings</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Help</a>
              </p>
            </div>
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">Contact US</h6>
              <p><i class="fas fa-home me-3"></i> INDIA</p>
              <p>
                <i class="fas fa-envelope me-3"></i>
                ord@yahoo.com
              </p>
              <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
              <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->

      <!-- Copyright -->
      <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2022 Copyright:
        <a class="text-reset fw-bold" href="{% url 'core:home' %}">ORD.com</a>
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-color">
  <div class="container-fluid">
    <img src="/static/css/logo1.png" style="height: 40px; width: 40px" />
    <a class="navbar-brand color-primary p-4" href="#"><b>ORD</b> </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link link-light active font poppins"
            aria-current="page"
            href="{% url 'core:home' %}"
            ><b>Home</b></a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link link-light active font poppins"
            href="{% url 'core:feedback_list' %}"
            ><b>Feedback</b></a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link link-light active font poppins"
            href="{% url 'core:about_us' %}"
            ><b>About US</b></a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link active poppins"
            href="{% url 'user:product_delivery' %}"
            >Delivery</a
          >
        </li>
      </ul>
      <form action="{% url 'core:product_search' %}" class="d-flex" role="search">
        <input
          class="form-control me-2 fst-italic mt-4"
          type="search"
          placeholder="Search"
          aria-label="Search"
          name="q"
        />
        <button class="btn btn-outline-primary mt-3 m-2" type="submit">Search</button>
      </form>
      <ul class="navbar-nav me-2 mb-2">
        <li class="nav-item dropdown m-2">
          {% if user.is_authenticated %} {% if user.profilemodel %}
          <a
            class="nav-link active font-1 mt-4 p-2 poppins"
            href="{% url 'user:profile_detail' user.profilemodel.id %}"
          >
            <b>{{user}}</b>
          </a>
          {% else %}
          <a
            class="nav-link active font-7 mt-4 p-2 poppins"
            href="{% url 'user:profile_create' %}"
          >
            <b>{{user}}</b>
          </a>
          {% endif %} {% else %}
          <a
            class="nav-link dropdown-toggle"
            href=""
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="fa-regular fa-user fa-2x"></i>
          </a>
          <ul class="dropdown-menu me-2">
            <li>
              <a class="dropdown-item" href="{% url 'user:user_login' %}"
                >Login</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'user:user_signup' %}"
                >Signup</a
              >
            </li>
          </ul>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a
            href="{% url 'user:user_logout' %}"
            class="nav-link active p-2 font-7 roboto mt-4"
            ><div class="row mt-4">
              Logout
            </div>
            <div class="row mb-2">
              <i class="fa-solid fa-right-from-bracket"></i>
            </div>
          </a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/scripts.html
{% load static %}

<!-- <script src="{% static 'jquery-3.6.1.min.js' %}"></script> -->
<script src="{% static 'bootstrap-5.2.1-dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'fontawesome-free-6.2.0-web/js/all.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

templates/includes/styles.html
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;1,100;1,200&family=Roboto:wght@400;500;900&display=swap" rel="stylesheet"> 
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;900&display=swap" rel="stylesheet"> 

<link rel="stylesheet" href="{% static 'bootstrap-5.2.1-dist/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'fontawesome-free-6.2.0-web/css/all.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">