core/urls.py
from django.urls import path
from core import views

app_name="core"
urlpatterns=[
    # common
    path("",views.HomeView.as_view(),name="home"),
    path("about/",views.AboutView.as_view(),name="about_us"),
    path("action/",views.ActionView.as_view(),name="choose_action"),
    # search
    path("product/search/",views.ProductSearchView.as_view(),name="product_search"),
    # feedback
    path("feedback_create/",views.FeedbackCreateView.as_view(),name="feedback_create"),
    path("feedback_list/",views.FeedbackListView.as_view(),name="feedback_list"),
    # product
    path("view_list/",views.ProductListView.as_view(),name="product_list"),
    path("card/<int:pk>/product/purchase/",views.ProductPurchaseView.as_view(),name="product_purchase"),
    # category
    path("card_list/",views.CardListView.as_view(),name="card_list"),
    # product by card
    path("product_by_card/<int:pk>/list/",views.ProductByCardView.as_view(),name="product_by_card"),
    # cart ckeckout
    path("cart/checkout/",views.CheckOutView.as_view(),name="cart_checkout"),
    # product summary
    path("product_summary/",views.ProductSummaryView.as_view(),name="product_summary"),
    # payment
    path("payment/",views.PaymentView.as_view(),name="payment"),
    # success
    path("success/",views.SuccessView.as_view(),name="success"),
]

online_ration_delivery/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("core.urls",namespace="core")),
    path("user/",include("user.urls",namespace="user")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from core import views
from user import views


app_name = "user"

urlpatterns = [
    path("sign_up/", views.UserCreateView.as_view(), name = "user_signup"),
    path("login/", views.UserLoginView.as_view(), name = "user_login"),
    path("logged_out/",views.UserLogoutView.as_view(),name="user_logout"),
    # card details
    path("card_details/",views.CardDetailView.as_view(),name="card_details"),
    # profile
    path("profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("profile/<int:pk>/detail/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/<int:pk>/update/",views.ProfileUpdateView.as_view(),name="profile_update"), 
    # address
    path("add_address/",views.AddressCreateView.as_view(),name="add_address"),
    path("address/<int:pk>/update/",views.AddressUpdateView.as_view(),name="address_update"),
    path("product_delivery/",views.DeliveryDetailView.as_view(),name="product_delivery"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from core import models as core_models
from django.urls import reverse

USER = settings.AUTH_USER_MODEL
class CustomUser(AbstractUser):
    pass

class LocationModel(models.Model):
    lattitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return f"{self.lattitude},{self.longitude}"
class AddressModel(models.Model):
    name=models.CharField(max_length=50)
    phone_number=models.CharField(max_length=15)
    building_name = models.CharField(max_length=64)
    place = models.CharField(max_length=32)
    city = models.CharField(max_length=32)
    district = models.CharField(max_length=32)
    state = models.CharField(max_length=32)
    country = models.CharField(max_length=24, default="India")
    postal_code = models.CharField(max_length=6)
    location = models.ForeignKey(
        LocationModel, on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.building_name},{self.place}-{self.postal_code}"


class ProfileModel(models.Model):
    GENDER_CHOICES = (
        ("M", "Male"),
        ("F", "Female"),
        ("O", "Others"),
    )
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    gender = models.CharField(max_length=15, choices=GENDER_CHOICES)
    image = models.ImageField(upload_to="user/profile/image/", default="default/user.png")
    phone_number = models.CharField(max_length=15)
    card_type=models.ManyToManyField(core_models.CardModel, blank=True)
    email=models.EmailField(max_length=100)
    address = models.ManyToManyField(AddressModel, blank=True)
    user = models.OneToOneField(USER, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}".title()

    def get_absolute_url(self):
        url=reverse("user:profile_detail",kwargs={'pk':self.id})

    

user/forms.py
from django import forms
from user import models as user_models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

USER = get_user_model()

# User Registration Form
class UserRegisterform(UserCreationForm):
    class Meta:
        model = USER
        fields = ["email", "username"]

class ProfileForm(forms.ModelForm):
    class Meta:
        model = user_models.ProfileModel
        exclude = ("status","updated_on","created_on","user","address")

class AddressForm(forms.ModelForm):
    class Meta:
        model = user_models.AddressModel
        exclude = ("status","updated_on","created_on")

user/views.py
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth import forms as auth_forms
from django.contrib import messages
from user import forms as user_form
from user import models as user_models
# from user import models

USER = get_user_model()

# UserCreateView
class UserCreateView(views.CreateView):
    template_name = "registration/sign_up.html"
    form_class = user_form.UserRegisterform
    success_url = reverse_lazy("user:user_login")

# user login
class UserLoginView(views.View):
    form_class = auth_forms.AuthenticationForm
    success_url = reverse_lazy("core:home")
    template_name = "registration/login.html"

    def get(self, request):
        context = {
            "form": self.form_class(),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request=request)
        # if form.is_valid():
        form.is_valid()
        username = request.POST.get("username")
        password = request.POST.get("password")
        # to check whether the given username and password are exists or not
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # to login user
            login(request, user)
            messages.success(request,"Login Successfully !")
            return redirect(self.success_url)
        messages.error(request,"Invalid User")
        context = {"form": form}
        return render(request, self.template_name, context)

# user logout
class UserLogoutView(views.View):
    template_name="registration/logged_out.html"
    def get(self,request):
        logout(request)
        messages.info(request,"Logged Out Successfully..")
        return render(request,self.template_name)


# view card details
class CardDetailView(views.TemplateView):
    template_name="registration/card_details.html"

#----------------------- profile-------------

class ProfileCreateView(views.CreateView):
    template_name = "user/profile_create.html"
    model = user_models.ProfileModel
    form_class = user_form.ProfileForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    

# profile updateview
class ProfileUpdateView(views.UpdateView):
    template_name = "user/profile_update.html"
    model = user_models.ProfileModel
    form_class = user_form.ProfileForm
    success_url = reverse_lazy("user:profile_detail")

class ProfileDetailView(views.TemplateView):
    template_name = "user/profile_detail.html"
    model = user_models.ProfileModel
    context_object_name = "profile"


# delivery
class DeliveryDetailView(views.TemplateView):
    template_name = "delivery/delivery.html"
    model = user_models.AddressModel
    context_object_name = "address"

# address create
class AddressCreateView(views.CreateView):
    template_name="delivery/new_address.html"
    model=user_models.AddressModel
    form_class = user_form.AddressForm
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
        
# address update
class AddressUpdateView(views.UpdateView):
    template_name = "delivery/address_update.html"
    model = user_models.AddressModel
    form_class = user_form.AddressForm
    success_url = reverse_lazy("user:delivery_detail")
    

templates/user/profile_create.html
{% extends 'base.html' %}{% block content %}

<body class="gradient-profile">
    <div class="container py-5 font times m-50">
        <form action="" method="post">
            {% csrf_token %}
            <table colspan="5">
                <tbody>
                    {{form.as_p}}
                </tbody>
            </table>
            
            <div class="text-center">
                <button type="submit" class="btn btn-primary font">Save</button>
            </div>
        </form>
    
    </div>                
</body>
{% endblock content %}

templates/user/profile_detail.html
{% extends 'base.html' %}{% block content %}

<section class="gradient-profile" style="min-height:100vh">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div
            class="rounded-top text-white d-flex flex-row"
            style="background-color: #000; height: 200px"
          >
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px">
              {% if user.profilemodel %}
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp"
                alt="Generic placeholder image"
                class="img-fluid img-thumbnail mt-4 mb-2"
                style="width: 150px; z-index: 1"
              />
              
              <button
                type="button"
                class="btn btn-outline-dark"
                data-mdb-ripple-color="dark"
                style="z-index: 1"
              >
                <a href="{% url 'user:profile_update' user.profilemodel.id %}">Edit profile
              </button></a>
            </div>
            <div class="ms-3" style="margin-top: 130px">
              <h5 class="text-capitalize">{{user.profilemodel.user}}</h5>
              <p>{{user.profilemodel.card_type}}</p>
            </div>
          </div>
          <div class="card">
            <div class="card-body p-4 text-black">
              <div class="mb-5 text-center">
                <p class="lead fw-normal mt-5 text-center">About</p>
                <div class="pt-1" style="background-color: #f8f9fa">
                  <p class="font-italic mb-1 text-capitalize">
                    First_name : {{user.profilemodel.first_name}}</p>
                  <p class="font-italic mb-1 text-capitalize">
                    Last_name : {{user.profilemodel.last_name}}</p>
                  <p class="font-italic mb-1 text-capitalize">
                    Gender : {{user.profilemodel.gender}}</p>
                  <p class="font-italic mb-1">
                    phone_number : {{user.profilemodel.phone_number}}</p>
                </div>
             
              </div> 
              {% else %}
                <tr>
                  <td colspan="5">
                    <a href="{% url 'user:profile_create' %}" class="text-light">
                    Create Profile
                    </a>
                  </td>
                </tr>             
              {% endif %}                    
            </div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/user/profile_update.html
{% extends 'base.html' %}{% block content %}

<body class="gradient-profile">
    <div class="container py-5 font times m-50">
        <div class="bg-light py-5 p-3">
            <form action="" method="post">
                {% csrf_token %}
                <table colspan="5">
                    <tbody>
                        {{form.as_p}}
                    </tbody>
                </table>
                
                <div class="text-center">
                    <button type="submit" class="btn btn-primary font">Save</button>
                </div>
            </form>
        </div>
    </div>                   
</body>
{% endblock content%}